// BlueOcean Game Providers
export enum BlueOceanGameProviders {
  '5men_games' = '5m',
  'arcadem' = 'ad',
  'felix' = 'ae',
  'amatic' = 'am',
  'amigo_gaming' = 'ao',
  'avatarux' = 'av',
  'aviatrix' = 'ax',
  'blueprint_premium' = 'b2',
  'big_time_gaming_evo' = 'b3',
  'bgaming' = 'ba',
  'bf_games' = 'bf',
  '3oaks' = 'bn',
  'blueprint' = 'bp',
  'barbarabang' = 'br',
  'betsoft' = 'bs',
  'blue_guru_oryx' = 'bu',
  'betixon' = 'bx',
  'betconstruct_slots' = 'c2',
  'popok_gaming' = 'c3',
  'xplosive_pro' = 'cp',
  'xplosive' = 'cs',
  'ct_gaming' = 'ct',
  'dragon_gaming' = 'da',
  'galaxsys' = 'df',
  'dragoon_soft' = 'dr',
  'amusnet' = 'e2',
  'ela_games' = 'e6',
  'mirage_gaming' = 'ec',
  'elk' = 'el',
  'espresso' = 'eo',
  'evoplay' = 'ep',
  'endorphina' = 'er',
  'elbet' = 'et',
  'fbm' = 'fb',
  'fachai' = 'fc',
  'fugaso' = 'fg',
  'fantasma' = 'fs',
  'fazi' = 'fz',
  'gameart_premium_gold' = 'g3',
  'booming_games' = 'gb',
  'gaming_corps' = 'go',
  'golden_race' = 'gr',
  'gameart' = 'gs',
  'g_games' = 'gv',
  'gaming_corps_premium' = 'gx',
  'gamzix' = 'gz',
  'caleta' = 'h8',
  'habanero' = 'ha',
  'hacksaw' = 'hs',
  'iron_dog' = 'id',
  'igtech' = 'ig',
  'isoftbet_premium' = 'ip',
  'isoftbet' = 'is',
  'jili' = 'ji',
  'kalamba' = 'ka',
  'king_midas' = 'km',
  'slotmotion' = 'ks',
  'kiron' = 'kv',
  'leap' = 'le',
  'mascot' = 'ma',
  'big_time_gaming_premium_gg' = 'md',
  'merkur' = 'mk',
  'mancala_gaming' = 'mm',
  'mrslotty' = 'mt',
  'nsoft_lottery' = 'n1',
  'netent' = 'n2',
  'netent_premium' = 'n3',
  'nolimit_city_evo' = 'n4',
  'novomatic_n2_premium' = 'nc',
  'realliveslots' = 'nd',
  'nolimit_city' = 'no',
  'nsoft' = 'ns',
  'novomatic_n2' = 'nt',
  'nextspin' = 'nx',
  'one_touch' = 'o2',
  'onegame' = 'om',
  'pragmatic_play' = 'p0',
  'playtech' = 'p5',
  'popiplay' = 'p8',
  'wizard_games' = 'pa',
  'petersons' = 'pd',
  'playpearls' = 'pe',
  'pg_soft' = 'pf',
  'playn_go' = 'pg',
  'salsa' = 'pn',
  'wizard_games_premium' = 'pp',
  'push' = 'pu',
  'playson_premium' = 'px',
  'playson' = 'py',
  'reelplay_relax' = 'q3',
  'felt_relax' = 'qf',
  'relax' = 'qr',
  'quickspin' = 'qs',
  'red_tiger' = 'r3',
  'red_tiger_premium' = 'r4',
  'ride_along' = 'ra',
  'boongo_red_genn' = 'rb',
  'redrake' = 'rk',
  'royal_slot_gaming' = 'rn',
  'rubyplay' = 'ru',
  'revolver' = 'rv',
  'swintt_premium' = 's2',
  'stakelogic_premium' = 's3',
  'slotopia' = 's6',
  'shadylady' = 'sd',
  'spadegaming' = 'sg',
  'slotmatrix' = 'sh',
  'spinthon' = 'si',
  'spinmatic' = 'sm',
  'slotmill' = 'so',
  'spinomenal' = 'sp',
  'spribe' = 'sr',
  'smartsoft' = 'ss',
  'stakelogic' = 'st',
  'swintt' = 'sw',
  'synot' = 'sy',
  'turbo_games' = 'ta',
  'egt_digital' = 'td',
  'pateplay' = 'te',
  'real_time_gaming' = 'tg',
  'tomhorn' = 'th',
  'thunderkick' = 'tk',
  'toka' = 'to',
  'triple_pg' = 'tp',
  'vibra_gaming' = 'vb',
  'vibra_gaming_premium' = 'vp',
  'qora' = 'wo',
  'voltent' = 'wz',
  '1x2_gaming' = 'xg',
  'expanse' = 'xn',
  'yggdrasil' = 'yg',
  'parlaybay' = 'aa',
  'digitain_sportsbook' = 'di',
  'tfgaming' = 'tf',
  'hot_slot_games' = 'hf',
}

// BlueOcean Game Types
export enum BlueOceanGameTypes {
  'livecasino' = 'livecasino',
  'poker' = 'poker',
  'virtual-sports' = 'virtual-sports',
  'sportsbook' = 'sportsbook',
  'live-casino-table' = 'live-casino-table',
  'video-slots' = 'video-slots',
  'table-games' = 'table-games',
  'video-poker' = 'video-poker',
  'virtual-games' = 'virtual-games',
  'scratch-cards' = 'scratch-cards',
  'video-bingo' = 'video-bingo',
  'tournaments' = 'tournaments',
  'livegames' = 'livegames',
  'crash-games' = 'crash-games',
  'fast-games' = 'fast-games',
}

// Type aliases for easier usage
export type BlueOceanProviderType = keyof typeof BlueOceanGameProviders
export type BlueOceanGameType = keyof typeof BlueOceanGameTypes

// Common provider aliases for frontend usage
export const BlueOceanProviderAliases = {
  PRAGMATIC: BlueOceanGameProviders.pragmatic_play,
  NETENT: BlueOceanGameProviders.netent,
  PLAYTECH: BlueOceanGameProviders.playtech,
  PLAYN_GO: BlueOceanGameProviders.playn_go,
  BGAMING: BlueOceanGameProviders.bgaming,
  EVOPLAY: BlueOceanGameProviders.evoplay,
  SPINOMENAL: BlueOceanGameProviders.spinomenal,
  RED_TIGER: BlueOceanGameProviders.red_tiger,
  QUICKSPIN: BlueOceanGameProviders.quickspin,
  THUNDERKICK: BlueOceanGameProviders.thunderkick,
  YGGDRASIL: BlueOceanGameProviders.yggdrasil,
} as const

// Common type aliases for frontend usage
export const BlueOceanTypeAliases = {
  SLOT: BlueOceanGameTypes['video-slots'],
  LIVE: BlueOceanGameTypes.livecasino,
  TABLE: BlueOceanGameTypes['table-games'],
  POKER: BlueOceanGameTypes.poker,
  BINGO: BlueOceanGameTypes['video-bingo'],
  SCRATCH: BlueOceanGameTypes['scratch-cards'],
  CRASH: BlueOceanGameTypes['crash-games'],
  FAST: BlueOceanGameTypes['fast-games'],
} as const
