export interface GameDataTypes {
  id: string
  gameName: string
  gameCode?: string        // gameId from blueoceangames (e.g., "176130")
  providerCode?: string    // provider from blueoceangames (e.g., "p0")
  gameType?: 'slots' | 'live-casino'
  player: string
  betAmount: number
  multiplier: string
  profit: number
  currency: '$' | '₿'
}

export interface TabData {
  [key: string]: GameDataTypes[]
}

export const dummyData: TabData = {
  'Latest Wins': [
    {
      id: '1',
      gameName: 'Gates of Olympus',
      gameCode: '176130',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'val***',
      betAmount: 596,
      multiplier: '1.61x',
      profit: 953.6,
      currency: '$',
    },
    {
      id: '2',
      gameName: 'Sweet Bonanza',
      gameCode: '176125',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'rel***',
      betAmount: 3435,
      multiplier: '2.00x',
      profit: 6870.0,
      currency: '₿',
    },
    {
      id: '3',
      gameName: 'Big Bass Bonanza',
      gameCode: '175892',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'etg***',
      betAmount: 45466,
      multiplier: '13.11x',
      profit: 595604.0,
      currency: '$',
    },
    {
      id: '4',
      gameName: 'Sugar Rush',
      gameCode: '176428',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'sdg***',
      betAmount: 12435,
      multiplier: '1.1x',
      profit: 13678.5,
      currency: '$',
    },
    {
      id: '5',
      gameName: 'The Dog House',
      gameCode: '175935',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'wfj***',
      betAmount: 46344,
      multiplier: '0.2x',
      profit: 9268.8,
      currency: '₿',
    },
    {
      id: '6',
      gameName: 'Starlight Princess',
      gameCode: '176223',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'wwr***',
      betAmount: 1234,
      multiplier: '0.435x',
      profit: 536.79,
      currency: '$',
    },
    {
      id: '7',
      gameName: 'Wolf Gold',
      gameCode: '176089',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'pjg***',
      betAmount: 3235,
      multiplier: '0.55x',
      profit: 1779.25,
      currency: '₿',
    },
    {
      id: '8',
      gameName: 'Mustang Gold',
      gameCode: '176003',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'wfx***',
      betAmount: 11150,
      multiplier: '2.35x',
      profit: 26216.6,
      currency: '$',
    },
  ],
  'High Rollers': [
    {
      id: '9',
      gameName: 'The Dog House Megaways',
      gameCode: '176245',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'vre***',
      betAmount: 56677,
      multiplier: '4.1x',
      profit: 232377.7,
      currency: '$',
    },
    {
      id: '10',
      gameName: 'Buffalo King Megaways',
      gameCode: '176334',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'qer***',
      betAmount: 87674,
      multiplier: '2.4x',
      profit: 210417.6,
      currency: '₿',
    },
    {
      id: '11',
      gameName: 'Madame Destiny Megaways',
      gameCode: '176156',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'abc***',
      betAmount: 75000,
      multiplier: '1.8x',
      profit: 135000,
      currency: '$',
    },
    {
      id: '12',
      gameName: 'John Hunter Aztec',
      gameCode: '176061',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'xyz***',
      betAmount: 92000,
      multiplier: '0.9x',
      profit: 82800,
      currency: '₿',
    },
    {
      id: '13',
      gameName: 'Wild West Gold',
      gameCode: '176320',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'def***',
      betAmount: 65000,
      multiplier: '3.2x',
      profit: 208000,
      currency: '$',
    },
  ],
  'Best Multipliers': [
    {
      id: '14',
      gameName: 'Gates of Olympus',
      gameCode: '176130',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'mno***',
      betAmount: 1200,
      multiplier: '50.0x',
      profit: 60000,
      currency: '$',
    },
    {
      id: '15',
      gameName: 'Sweet Bonanza',
      gameCode: '176125',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'pqr***',
      betAmount: 800,
      multiplier: '45.5x',
      profit: 36400,
      currency: '₿',
    },
    {
      id: '16',
      gameName: 'Starlight Princess',
      gameCode: '176223',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'stu***',
      betAmount: 2500,
      multiplier: '25.8x',
      profit: 64500,
      currency: '$',
    },
    {
      id: '17',
      gameName: 'Big Bass Bonanza',
      gameCode: '175892',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'vwx***',
      betAmount: 1500,
      multiplier: '32.1x',
      profit: 48150,
      currency: '₿',
    },
    {
      id: '18',
      gameName: 'Sugar Rush',
      gameCode: '176428',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'yza***',
      betAmount: 3000,
      multiplier: '18.7x',
      profit: 56100,
      currency: '$',
    },
  ],
  'Winners of the Day': [
    {
      id: '19',
      gameName: 'Wolf Gold',
      gameCode: '176089',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'bcd***',
      betAmount: 5000,
      multiplier: '8.5x',
      profit: 42500,
      currency: '$',
    },
    {
      id: '20',
      gameName: 'Mustang Gold',
      gameCode: '176003',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'efg***',
      betAmount: 7500,
      multiplier: '6.2x',
      profit: 46500,
      currency: '₿',
    },
    {
      id: '21',
      gameName: 'The Dog House',
      gameCode: '175935',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'hij***',
      betAmount: 4200,
      multiplier: '9.1x',
      profit: 38220,
      currency: '$',
    },
    {
      id: '22',
      gameName: 'Great Rhino Megaways',
      gameCode: '176099',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'klm***',
      betAmount: 6800,
      multiplier: '5.5x',
      profit: 37400,
      currency: '₿',
    },
  ],
  'Winners of the Month': [
    {
      id: '23',
      gameName: 'The Dog House Megaways',
      gameCode: '176245',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'nop***',
      betAmount: 25000,
      multiplier: '12.4x',
      profit: 310000,
      currency: '$',
    },
    {
      id: '24',
      gameName: 'Buffalo King Megaways',
      gameCode: '176334',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'qrs***',
      betAmount: 18000,
      multiplier: '15.6x',
      profit: 280800,
      currency: '₿',
    },
    {
      id: '25',
      gameName: 'Gates of Olympus',
      gameCode: '176130',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'tuv***',
      betAmount: 30000,
      multiplier: '8.9x',
      profit: 267000,
      currency: '$',
    },
    {
      id: '26',
      gameName: 'Sweet Bonanza',
      gameCode: '176125',
      providerCode: 'p0',
      gameType: 'slots',
      player: 'wxy***',
      betAmount: 22000,
      multiplier: '11.2x',
      profit: 246400,
      currency: '₿',
    },
  ],
}
