export const TRANSACTION_STATUS: any = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  PROCESSING: 'PROCESSING',
  EXPIRED: 'EXPIRED',
  APPROVED: 'APPROVED',
}

export const VAULTODY_TX_EVENTS: any = {
  TRANSACTION_REQUEST: 'TRANSACTION_REQUEST',
  TRANSACTION_APPROVED: 'TRANSACTION_APPROVED',
  TRANSACTION_REJECTED: 'TRANSACTION_REJECTED',
  INCOMING_CONFIRMED_COIN_TX: 'INCOMING_CONFIRMED_COIN_TX',
  INCOMING_CONFIRMED_TOKEN_TX: 'INCOMING_CONFIRMED_TOKEN_TX',
  INCOMING_CONFIRMED_INTERNAL_TX: 'INCOMING_CONFIRMED_INTERNAL_TX',
  INCOMING_MINED_TX: 'INCOMING_MINED_TX',
  OUTGOING_FAILED: 'OUTGOING_FAILED',
  OUTGOING_MINED: 'OUTGOING_MINED',
  TRANSACTION_BROADCASTED: 'TRANSACTION_BROADCASTED',
}

export const VAULTODY_TRANSACTION_STATUS_MAP: any = {
  [VAULTODY_TX_EVENTS.INCOMING_MINED_TX]: TRANSACTION_STATUS.PROCESSING,
  [VAULTODY_TX_EVENTS.TRANSACTION_REQUEST]: TRANSACTION_STATUS.PENDING,
  [VAULTODY_TX_EVENTS.TRANSACTION_APPROVED]: TRANSACTION_STATUS.APPROVED,
  [VAULTODY_TX_EVENTS.TRANSACTION_REJECTED]: TRANSACTION_STATUS.FAILED,
  [VAULTODY_TX_EVENTS.INCOMING_CONFIRMED_COIN_TX]:
    TRANSACTION_STATUS.PROCESSING,
  [VAULTODY_TX_EVENTS.INCOMING_CONFIRMED_TOKEN_TX]:
    TRANSACTION_STATUS.PROCESSING,
  [VAULTODY_TX_EVENTS.INCOMING_CONFIRMED_INTERNAL_TX]:
    TRANSACTION_STATUS.PROCESSING,
}
